// Builds src/elevation.ts from data/earth-topology.png.
//
// The PNG is the equirectangular grayscale topography map shipped with the
// three-globe project (github.com/vasturiano/three-globe, MIT), derived from
// NASA imagery. Brightness tracks elevation at roughly 25 m per step
// (Boise 37, Denver 63, Tibet 193, Everest 228), oceans are 0.
//
//   node scripts/elevation.mjs
import fs from 'node:fs';
import { PNG } from 'pngjs';
import { contours } from 'd3-contour';

const M_PER_STEP = 25;
const png = PNG.sync.read(fs.readFileSync(new URL('../data/earth-topology.png', import.meta.url)));

// Downsample to a 0.5° grid (720 x 360), averaging each block.
function grid(w, h) {
  const out = new Float64Array(w * h), fx = png.width / w, fy = png.height / h;
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    let s = 0, n = 0;
    for (let j = Math.floor(y * fy); j < Math.floor((y + 1) * fy); j++)
      for (let i = Math.floor(x * fx); i < Math.floor((x + 1) * fx); i++) { s += png.data[4 * (j * png.width + i)]; n++; }
    out[y * w + x] = s / n;
  }
  return out;
}
// A light box blur so contours read as smooth hand-drawn lines.
function blur(v, w, h) {
  const o = new Float64Array(v.length);
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    let s = 0, n = 0;
    for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) {
      const yy = y + dy, xx = (x + dx + w) % w;
      if (yy < 0 || yy >= h) continue;
      s += v[yy * w + xx]; n++;
    }
    o[y * w + x] = s / n;
  }
  return o;
}

// Ramer-Douglas-Peucker, so each ring keeps its shape with far fewer points.
function simplify(pts, tol) {
  if (pts.length < 4) return pts;
  const keep = new Uint8Array(pts.length); keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop(); let best = 0, idx = -1;
    const [ax, ay] = pts[a], [bx, by] = pts[b], dx = bx - ax, dy = by - ay, len = Math.hypot(dx, dy) || 1;
    for (let i = a + 1; i < b; i++) { const d = Math.abs(dy * pts[i][0] - dx * pts[i][1] + bx * ay - by * ax) / len; if (d > best) { best = d; idx = i; } }
    if (best > tol) { keep[idx] = 1; stack.push([a, idx], [idx, b]); }
  }
  return pts.filter((_, i) => keep[i]);
}

/* Closed rings start and end on the same point, so split at the far side first. */
function simplifyRing(pts, tol) {
  let far = 0, best = -1;
  pts.forEach(([x, y], i) => { const d = Math.hypot(x - pts[0][0], y - pts[0][1]); if (d > best) { best = d; far = i; } });
  if (far === 0) return [];
  return simplify(pts.slice(0, far + 1), tol).concat(simplify(pts.slice(far), tol).slice(1));
}

const W = 720, H = 360;
const field = blur(grid(W, H), W, H);
const LEVELS_M = [500, 1000, 2000, 3000, 4000];
const sx = 1000 / W, sy = 500 / H;
const paths = contours().size([W, H]).thresholds(LEVELS_M.map((m) => m / M_PER_STEP))(Array.from(field)).map((g) =>
  g.coordinates.map((poly) => poly
    .map((ring) => simplifyRing(ring.map(([x, y]) => [x * sx, y * sy]), 0.45))
    .filter((ring) => ring.length > 3)
    .map((ring) => 'M' + ring.map(([x, y]) => `${Math.round(x * 2) / 2} ${Math.round(y * 2) / 2}`).join('L') + 'Z').join('')).join(''),
);

// Pointer readout: a 1° grid, one byte per cell (steps of 25 m).
const coarse = grid(360, 180);  // 64,800 cells; mostly ocean zeros, so it gzips small
const bytes = Buffer.from(Array.from(coarse, (v) => Math.round(v)));

fs.writeFileSync(new URL('../src/elevation.ts', import.meta.url), `// Generated by scripts/elevation.mjs. Do not edit.
/** Contour levels in metres, low to high. */
export const LEVELS_M = ${JSON.stringify(LEVELS_M)};
/** One filled contour path per level, in the 1000 x 500 map space. */
export const CONTOURS: string[] = ${JSON.stringify(paths)};
/** Metres per step in ELEV_1DEG. */
export const M_PER_STEP = ${M_PER_STEP};
/** 360 x 180 grid, 1° cells from 90°N / 180°W, base64 bytes. */
export const ELEV_1DEG = '${bytes.toString('base64')}';
`);
console.log('levels', LEVELS_M, 'path chars', paths.map((p) => p.length), 'grid b64', bytes.toString('base64').length);
